README.adoc — kn-plugin-search

== kn-plugin-search

`kn plugin search` helps Knative users discover existing and new `kn` plugins. It is itself a plugin.

=== Description

With `kn-plugin-search` you can enhance your experience with Knative and its `kn` command line in two ways:

1. Searching and finding existing approved, alpha, and beta plugins shared by the community.

2. Getting salient details about `kn` plugins to help you decide if you want to try it. This also includes links to download the latest version of the plugin.

`kn-plugin-search` returns latest know plugins by scanning GitHub for projects that have a specific naming pattern (`kn-plugin-*`) and also maintains a list of approved and WIP projects by the human maintainers of this project.

=== Usage

----
`kn plugin search` helps Knative users discover existing and new `kn` plugins. It is itself a plugin.

Usage:
  kn plugin search [command]
  
Available Commands:
  help        Help about any command
  version     Prints the plugin version

Flags:
  -h, --help   help for kn-plugin-search
  -A, --all    returns all currently known plugins

Use "kn-plugin-search [command] --help" for more information about a command.
----

==== `kn plugin search`

----
Search for plugins that have name WORDS or whose name match REGEX

Usage:
  kn plugin search [WORDS | REGEX] [flags]

Flags:
  -h, --help   help for print
----

==== `kn plugin search version`

This command prints out the version of this plugin and all extra information which might help, for example when creating bug reports.

----
Prints the plugin version

Usage:
  kn plugin search version [flags]

Flags:
  -h, --help   help for version
----

=== Examples

==== Search for all known plugins

If you want to see the list of all known plugins (approved or not) then invoke without any parameters

.Example Greeting
====
----
$ kn plugin search

kn-plugin-diag 
alpha
A plugin to show Knative service diagnostic
https://github.com/knative-sandbox/kn-plugin-diag


kn-plugin-migration
alpha
A plugin to help you migrate one Knative cluster to another
https://github.com/knative-sandbox/kn-plugin-migration

…
----
====

==== Print out the version of this plugin

The `kn sample version` command helps you to identify the version of this plugin.

.Example version output
=====
-----
$ kn plugin search version

Version:      v20200402-local-a099aaf-dirty
Build Date:   2020-04-02 18:16:20
Git Revision: a099aaf
-----
=====

As you can see it prints out the version, (or a generated timestamp when this plugin is built from a non-released commit) the date when the plugin has been built and the actual Git revision.
